version: "3.9"
services:
  backend:
    container_name: backend
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./:/app
    environment:
      PORT: 1234
    ports:
      - 1234:1234
    depends_on:
      - db

  db:
    image: mongo:4.2.23-bionic
    container_name: db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./.mongo_db:/data/db

  mongo-express:
    image: mongo-express:0.54.0
    container_name: db-ui
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - db
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://user:password@db:27017/
